export const famousFilms = [
    "The Godfather",
    "The Shawshank Redemption",
    "Schindler's List",
    "Raging Bull",
    "Casablanca",
    "Citizen Kane",
    "Gone with the Wind",
    "The Wizard of Oz",
    "One Flew Over the Cuckoo's Nest",
    "Lawrence of Arabia",
    "Vertigo",
    "Psycho",
    "The Godfather Part II",
    "On the Waterfront",
    "Sunset Boulevard",
    "Forrest Gump",
    "Inception",
    "The Dark Knight",
    "Fight Club",
    "Pulp Fiction",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Matrix",
    "Goodfellas",
    "The Silence of the Lambs",
    "Se7en",
    "It's a Wonderful Life",
    "Saving Private Ryan",
    "American History X",
    "The Green Mile",
    "The Lion King",
    "Gladiator",
    "Jurassic Park",
    "Titanic",
    "Braveheart",
    "A Beautiful Mind",
    "Slumdog Millionaire",
    "Avatar",
    "Toy Story",
    "Finding Nemo",
    "Up",
    "Monsters, Inc.",
    "WALL-E",
    "The Incredibles",
    "Inside Out",
    "Ratatouille",
    "Coco",
    "Toy Story 3",
    "Toy Story 4",
    "Spider-Man: Into the Spider-Verse",
    "Black Panther",
    "Avengers: Endgame",
    "The Avengers",
    "Avengers: Infinity War",
    "Iron Man",
    "Captain America: The Winter Soldier",
    "Guardians of the Galaxy",
    "Thor: Ragnarok",
    "Doctor Strange",
    "Ant-Man",
    "Spider-Man: Homecoming",
    "Spider-Man: Far From Home",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "Logan",
    "Deadpool",
    "Deadpool 2",
    "X-Men: Days of Future Past",
    "X-Men: First Class",
    "X-Men",
    "X2",
    "X-Men: The Last Stand",
    "The Wolverine",
    "Hugh Jackman",
    "Days of Future Past",
    "First Class",
    "The Last Stand",
    "The Hunger Games",
    "The Hunger Games: Catching Fire",
    "The Hunger Games: Mockingjay - Part 1",
    "The Hunger Games: Mockingjay - Part 2",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Fantastic Beasts and Where to Find Them",
    "Fantastic Beasts: The Crimes of Grindelwald",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pirates of the Caribbean: At World's End",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "Indiana Jones and the Raiders of the Lost Ark",
    "Indiana Jones and the Temple of Doom",
    "Indiana Jones and the Last Crusade",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "E.T. the Extra-Terrestrial",
    "Jaws",
    "Close Encounters of the Third Kind",
    "Jurassic Park",
    "Jurassic World",
    "Jurassic World: Fallen Kingdom",
    "Star Wars: Episode IV - A New Hope",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Star Wars: Episode VI - Return of the Jedi",
    "Star Wars: Episode I - The Phantom Menace",
    "Star Wars: Episode II - Attack of the Clones",
    "Star Wars: Episode III - Revenge of the Sith",
    "Star Wars: The Force Awakens",
    "Star Wars: The Last Jedi",
    "Star Wars: The Rise of Skywalker",
    "Rogue One: A Star Wars Story",
    "Solo: A Star Wars Story",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Terminator 3: Rise of the Machines",
    "Terminator Salvation",
    "Terminator Genisys",
    "Terminator: Dark Fate",
    "Rocky",
    "Rocky II",
    "Rocky III",
    "Rocky IV",
    "Rocky V",
    "Rocky Balboa",
    "Creed",
    "Creed II",
    "The Exorcist",
    "The Shining",
    "A Nightmare on Elm Street",
    "Halloween",
    "Scream",
    "The Texas Chain Saw Massacre",
    "Friday the 13th",
    "Saw",
    "Saw II",
    "Saw III",
    "Saw IV",
    "Saw V",
    "Saw VI",
    "Saw 3D",
    "Jigsaw",
    "It",
    "It Chapter Two",
    "The Conjuring",
    "The Conjuring 2",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "The Nun",
    "The Curse of La Llorona",
    "Paranormal Activity",
    "Paranormal Activity 2",
    "Paranormal Activity 3",
    "Paranormal Activity 4",
    "Paranormal Activity: The Marked Ones",
    "Paranormal Activity: The Ghost Dimension",
    "Insidious",
    "Insidious: Chapter 2",
    "Insidious: Chapter 3",
    "Insidious: The Last Key",
    "The Blair Witch Project",
    "Blair Witch",
    "Sinister",
    "Sinister 2",
    "The Ring",
    "The Ring Two",
    "Rings",
    "Poltergeist",
    "Poltergeist II: The Other Side",
    "Poltergeist III",
    "Child's Play",
    "Child's Play 2",
    "Child's Play 3",
    "Bride of Chucky",
    "Seed of Chucky",
    "Curse of Chucky",
    "Cult of Chucky",
    "Alien",
    "Aliens",
    "Alien 3",
    "Alien: Resurrection",
    "Prometheus",
    "Alien: Covenant",
    "Predator",
    "Predator 2",
    "Predators",
    "The Predator",
    "Die Hard",
    "Die Hard 2",
    "Die Hard with a Vengeance",
    "Live Free or Die Hard",
    "A Good Day to Die Hard",
    "Mad Max: Fury Road",
    "Mad Max",
    "Mad Max 2: The Road Warrior",
    "Mad Max Beyond Thunderdome",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "John Wick",
    "John Wick: Chapter 2",
    "John Wick: Chapter 3 - Parabellum",
    "The Fast and the Furious",
    "2 Fast 2 Furious",
    "The Fast and the Furious: Tokyo Drift",
    "Fast & Furious",
    "Fast Five",
    "Fast & Furious 6",
    "Furious 7",
    "The Fate of the Furious",
    "F9",
    "Hobbs & Shaw",
    "Mission: Impossible",
    "Mission: Impossible 2",
    "Mission: Impossible III",
    "Mission: Impossible - Ghost Protocol",
    "Mission: Impossible - Rogue Nation",
    "Mission: Impossible - Fallout",
    "James Bond: Dr. No",
    "James Bond: From Russia with Love",
    "James Bond: Goldfinger",
    "James Bond: Thunderball",
    "James Bond: You Only Live Twice",
    "James Bond: On Her Majesty's Secret Service",
    "James Bond: Diamonds Are Forever",
    "James Bond: Live and Let Die",
    "James Bond: The Man with the Golden Gun",
    "James Bond: The Spy Who Loved Me",
    "James Bond: Moonraker",
    "James Bond: For Your Eyes Only",
    "James Bond: Octopussy",
    "James Bond: A View to a Kill",
    "James Bond: The Living Daylights",
    "James Bond: Licence to Kill",
    "James Bond: GoldenEye",
    "James Bond: Tomorrow Never Dies",
    "James Bond: The World Is Not Enough",
    "James Bond: Die Another Day",
    "James Bond: Casino Royale",
    "James Bond: Quantum of Solace",
    "James Bond: Skyfall",
    "James Bond: Spectre",
    "James Bond: No Time to Die",
    "Batman",
    "Batman Returns",
    "Batman Forever",
    "Batman & Robin",
    "Batman Begins",
    "The Dark Knight",
    "The Dark Knight Rises",
    "Man of Steel",
    "Batman v Superman: Dawn of Justice",
    "Suicide Squad",
    "Wonder Woman",
    "Wonder Woman 1984",
    "Justice League",
   
]  