export const famousFilms = [
    "The Godfather",
    "The Shawshank Redemption",
    "Schindler's List",
    "Raging Bull",
    "Casablanca",
    "Citizen Kane",
    "Gone with the Wind",
    "The Wizard of Oz",
    "One Flew Over the Cuckoo's Nest",
    "Lawrence of Arabia",
    "Vertigo",
    "Psycho",
    "The Godfather Part II",
    "On the Waterfront",
    "Sunset Boulevard",
    "Forrest Gump",
    "Inception",
    "The Dark Knight",
    "12 Angry Men",
    "The Good, the Bad and the Ugly",
    "Fight Club",
    "The Lord of the Rings: The Return of the King",
    "Star Wars",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "Pulp Fiction",
    "The Empire Strikes Back",
    "The Matrix",
    "Goodfellas",
    "The Silence of the Lambs",
    "Se7en",
    "It's a Wonderful Life",
    "The Usual Suspects",
    "Braveheart",
    "Gladiator",
    "Saving Private Ryan",
    "The Departed",
    "City of God",
    "Spirited Away",
    "Life is Beautiful",
    "Léon: The Professional",
    "The Intouchables",
    "Modern Times",
    "The Green Mile",
    "Interstellar",
    "The Pianist",
    "Back to the Future",
    "The Lion King",
    "American Beauty",
    "Memento",
    "The Prestige",
    "The Shining",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Alien",
    "Aliens",
    "The Breakfast Club",
    "Taxi Driver",
    "Jaws",
    "Jurassic Park",
    "E.T. the Extra-Terrestrial",
    "A Clockwork Orange",
    "The Bridge on the River Kwai",
    "Chinatown",
    "2001: A Space Odyssey",
    "The Great Escape",
    "The Seventh Seal",
    "The Thing",
    "Monty Python and the Holy Grail",
    "The Big Lebowski",
    "The Hunt for Red October",
    "The Grand Budapest Hotel",
    "Django Unchained",
    "The Revenant",
    "Whiplash",
    "Mad Max: Fury Road",
    "The Wolf of Wall Street",
    "Her",
    "Guardians of the Galaxy",
    "The Social Network",
    "Moonlight",
    "La La Land",
    "Get Out",
    "Three Billboards Outside Ebbing, Missouri",
    "Parasite",
    "The Shape of Water",
    "Lady Bird",
    "The Favourite",
    "Call Me by Your Name",
    "A Star is Born",
    "Roma",
    "Black Panther",
    "Spider-Man: Into the Spider-Verse",
    "Joker",
    "Once Upon a Time in Hollywood",
    "Knives Out",
    "Jojo Rabbit",
    "Ford v Ferrari",
    "1917",
    "Dunkirk",
    "The Irishman",
    "Once Upon a Time in America",
    "The Truman Show",
    "Eternal Sunshine of the Spotless Mind",
    "Fight Club",
    "A Beautiful Mind",
    "The Sixth Sense",
    "Glengarry Glen Ross",
    "Donnie Brasco",
    "The Boondock Saints",
    "Fargo",
    "The Royal Tenenbaums",
    "The Sixth Sense",
    "Requiem for a Dream",
    "American History X",
    "The Big Short",
    "No Country for Old Men",
    "The Departed",
    "Oldboy",
    "Memories of Murder",
    "Pan's Labyrinth",
    "The Hunt",
    "The Handmaiden",
    "The Lives of Others",
    "Crouching Tiger, Hidden Dragon",
    "Run Lola Run",
    "Wings of Desire",
    "Good Will Hunting",
    "Gangs of New York",
    "Donnie Darko",
    "The Pianist",
    "The English Patient",
    "The Last Emperor",
    "Out of Africa",
    "The Deer Hunter",
    "The French Connection",
    "Network",
    "Chariots of Fire",
    "The Killing Fields",
    "The Last Picture Show",
    "A Man for All Seasons",
    "The Deer Hunter",
    "All the President's Men",
    "The Conversation",
    "The Exorcist",
    "Rosemary's Baby",
    "Night of the Living Dead",
    "The Blair Witch Project",
    "The Texas Chain Saw Massacre",
    "The Evil Dead",
    "A Nightmare on Elm Street",
    "Halloween",
    "The Omen",
    "Psycho",
    "Jaws",
    "The Shining",
    "Hereditary",
    "The Witch",
    "Get Out",
    "The Babadook",
    "It Follows",
    "The Cabin in the Woods",
    "The Conjuring",
    "Sinister",
    "The Ring",
    "The Descent",
    "A Quiet Place",
    "The Invisible Man",
    "The Orphanage",
    "Pan's Labyrinth",
    "Let the Right One In",
    "The Others",
    "The Frighteners",
    "The Howling",
    "An American Werewolf in London",
    "The Thing",
    "The Wicker Man",
    "The Changeling",
    "The Entity",
    "The Amityville Horror",
    "The Beyond",
    "Suspiria",
    "The Babadook",
    "The Exorcism of Emily Rose",
    "The Conjuring 2",
    "Insidious",
    "The Nun",
    "The Visit",
    "Don't Breathe",
    "The Purge",
    "The Cabin in the Woods",
    "The Witch",
    "The Strangers",
    "The Gift",
    "Gerald's Game",
    "1922",
    "The Autopsy of Jane Doe",
    "The Killing of a Sacred Deer",
    "Mother!",
    "Cam",
    "Terrified",
    "The Belko Experiment",
    "The Invitation",
    "The Platform",
    "Ringu",
    "The Craft",
    "Hellraiser",
    "Tales from the Crypt: Demon Knight",
    "Idle Hands",
    "Waxwork",
    "Day Watch",
    "Night Watch",
    "Hellboy",
    "The Last Exorcism",
    "The Devil's Advocate",
    "The Skeleton Key",
    "Cloverfield",
    "The Taking of Deborah Logan",
    "The House of the Devil",
    "V/H/S",
    "The Lords of Salem",
    "The Autopsy of Jane Doe",
    "The Witch",
    "The Wailing",
    "The Orphanage",
    "The Devil's Candy",
    "A Girl Walks Home Alone at Night",
    "The Witch",
    "The Babadook",
    "Hereditary",
    "The Invitation",
    "Raw",
    "The Conjuring 2",
    "The Invisible Man",
    "A Quiet Place",
    "The Others",
    "The Orphanage",
    "The Mist",
    "The Strangers",
    "The Woman in Black",
    "The Grudge",
    "The Ring",
    "The Haunting",
    "The Omen",
    "The Exorcist",
    "Rosemary's Baby",
    "The Shining",
    "Get Out",
    "The Cabin in the Woods",
    "It Follows",
    "The Witch",
    "The Babadook",
    "Hereditary",
    "A Quiet Place",
    "The Invisible Man",
    "The Conjuring",
    "The Conjuring 2",
    "The Nun",
    "Insidious",
    "The Visit",
    "The Gift",
    "The Autopsy of Jane Doe",
    "The Devil's Candy",
    "The Platform",
    "The Belko Experiment",
    "The Night Comes for Us",
    "The Babadook",
    "The Witch",
    "The Wailing",
    "The Orphanage",
    "The Conjuring",
    "The Conjuring 2",
    "The Haunting",
    "The Ring",
    "The Grudge",
    "The Others",
    "Rosemary's Baby",
    "The Shining",
    "The Exorcist",
    "The Omen",
    "The Amityville Horror",
    "The Blair Witch Project",
    "The Texas Chain Saw Massacre",
    "The Evil Dead",
    "A Nightmare on Elm Street",
    "Halloween",
    "The Thing",
    "Let the Right One In",
    "Pan's Labyrinth",
    "The Witch",
    "The Babadook",
    "The Conjuring",
    "Get Out",
    "The Invisible Man",
    "The Haunting",
    "The Ring",
    "The Others",
    "The Strangers",
    "The Witch",
    "The Exorcist",
    "Rosemary's Baby",
    "The Shining",
    "The Omen",
    "The Texas Chain Saw Massacre",
    "The Evil Dead",
    "The Amityville Horror",
    "The Exorcism of Emily Rose",
    "The Conjuring 2",
    "The Wailing",
    "The Orphanage",
    "The Devil's Candy",
    "A Girl Walks Home Alone at Night",
    "The Witch",
    "The Babadook",
    "Hereditary",
    "The Invitation",
    "Raw",
    "The Conjuring 2",
    "The Invisible Man",
    "A Quiet Place",
    "The Others",
    "The Orphanage",
    "The Mist",
    "The Strangers",
    "The Woman in Black",
    "The Grudge",
    "The Ring",
    "The Haunting",
    "The Omen",
    "The Exorcist",
    "Rosemary's Baby",
    "The Shining",
    "Get Out",
    "The Cabin in the Woods",
    "It Follows",
    "The Witch",
    "The Babadook",
    "Hereditary",
    "A Quiet Place",
    "The Invisible Man",
    "The Conjuring",
    "The Conjuring 2",
    "The Nun",
    "Insidious",
    "The Visit",
    "The Gift",
    "The Autopsy of Jane Doe",
    "The Devil's Candy",
    "The Platform",
    "The Belko Experiment",
    "The Night Comes for Us",
    "The Babadook",
    "The Witch",
    "The Wailing",
    "The Orphanage",
    "The Conjuring",
    "The Conjuring 2",
    "The Haunting",
    "The Ring",
    "The Others",
    "The Strangers",
    "The Witch",
    "The Exorcist",
    "Rosemary's Baby",
    "The Shining",
    "The Omen",
    "The Texas Chain Saw Massacre",
    "The Evil Dead",
    "The Amityville Horror",
    "The Exorcism of Emily Rose",
    "The Conjuring 2",
    "A Clockwork Orange",
    "American History X",
    "Apocalypse Now",
    "Argo",
    "Arrival",
    "Atonement",
    "Avatar",
    "Babel",
    "Barry Lyndon",
    "Beauty and the Beast",
    "Before Sunrise",
    "Before Sunset",
    "Before Midnight",
    "Ben-Hur",
    "Big Fish",
    "Birdman",
    "Blade Runner",
    "Blade Runner 2049",
    "Blazing Saddles",
    "Blue Velvet",
    "Bonnie and Clyde",
    "Boogie Nights",
    "Brazil",
    "Breakfast at Tiffany's",
    "Pulp Fiction",
    "The Matrix",
    "Goodfellas",
    "The Silence of the Lambs",
    "Se7en",
    "It's a Wonderful Life",
    "The Usual Suspects",
    "Braveheart",
    "Gladiator",
    "Saving Private Ryan",
    "City of God",
    "Spirited Away",
    "Life is Beautiful",
    "Léon: The Professional",
    "The Intouchables",
    "Modern Times",
    "The Green Mile",
    "Interstellar",
    "Back to the Future",
    "The Lion King",
    "American Beauty",
    "Memento",
    "The Prestige",
    "The Shining",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Alien",
    "Aliens",
    "The Breakfast Club",
    "Taxi Driver",
    "Jaws",
    "Jurassic Park",
    "E.T. the Extra-Terrestrial",
    "A Clockwork Orange",
    "The Bridge on the River Kwai",
    "Chinatown",
    "2001: A Space Odyssey",
    "The Great Escape",
    "The Seventh Seal",
    "The Thing",
    "Monty Python and the Holy Grail",
    "The Big Lebowski",
    "The Hunt for Red October",
    "The Grand Budapest Hotel",
    "Django Unchained",
    "The Revenant",
    "Whiplash",
    "Mad Max: Fury Road",
    "The Wolf of Wall Street",
    "Her",
    "Guardians of the Galaxy",
    "The Social Network",
    "Moonlight",
    "La La Land",
    "Get Out",
    "Three Billboards Outside Ebbing, Missouri",
    "Parasite",
    "The Shape of Water",
    "Lady Bird",
    "The Favourite",
    "Call Me by Your Name",
    "A Star is Born",
    "Roma",
    "Black Panther",
    "Spider-Man: Into the Spider-Verse",
    "Joker",
    "Once Upon a Time in Hollywood",
    "Knives Out",
    "Jojo Rabbit",
    "Ford v Ferrari",
    "1917",
    "Dunkirk",
    "The Irishman",
    "Once Upon a Time in America",
    "The Truman Show",
    "Eternal Sunshine of the Spotless Mind",
    "A Beautiful Mind",
    "The Sixth Sense",
    "Glengarry Glen Ross",
    "Donnie Brasco",
    "The Boondock Saints",
    "Fargo",
    "The Royal Tenenbaums",
    "Requiem for a Dream",
    "American History X",
    "The Big Short",
    "No Country for Old Men",
    "Oldboy",
    "Memories of Murder",
    "Pan's Labyrinth",
    "The Hunt",
    "The Handmaiden",
    "The Lives of Others",
    "Crouching Tiger, Hidden Dragon",
    "Run Lola Run",
    "Wings of Desire",
    "Good Will Hunting",
    "Gangs of New York",
    "Donnie Darko",
    "The English Patient",
    "The Last Emperor",
    "Out of Africa",
    "The Deer Hunter",
    "The French Connection",
    "Network",
    "Chariots of Fire",
    "The Killing Fields",
    "The Last Picture Show",
    "A Man for All Seasons",
    "All the President's Men",
    "The Conversation",
    "The Exorcist",
    "Rosemary's Baby",
    "Night of the Living Dead",
    "The Blair Witch Project",
    "The Texas Chain Saw Massacre",
    "The Evil Dead",
    "A Nightmare on Elm Street",
    "Halloween",
    "The Omen",
    "Psycho",
    "Jaws",
    "The Shining",
    "Hereditary",
    "The Witch",
    "Get Out",
    "The Babadook",
    "It Follows",
    "The Cabin in the Woods",
    "Sinister",
    "The Ring",
    "The Descent",
    "A Quiet Place",
    "The Invisible Man",
    "The Orphanage",
    "Let the Right One In",
    "The Others",
    "The Frighteners",
    "The Howling",
    "An American Werewolf in London",
    "The Wicker Man",
    "The Changeling",
    "The Entity",
    "The Amityville Horror",
    "The Beyond",
    "Suspiria",
    "The Exorcism of Emily Rose",
    "The Conjuring 2",
    "Insidious",
    "The Nun",
    "The Visit",
    "Don't Breathe",
    "The Purge",
    "The Witch",
    "The Strangers",
    "The Gift",
    "Gerald's Game",
    "1922",
    "The Autopsy of Jane Doe",
    "The Killing of a Sacred Deer",
    "Mother!",
    "Cam",
    "Terrified",
    "The Belko Experiment",
    "The Invitation",
    "The Platform",
    "Ringu",
    "The Craft",
    "Hellraiser",
    "Tales from the Crypt: Demon Knight",
    "Idle Hands",
    "Waxwork",
    "Day Watch",
    "Night Watch",
    "Hellboy",
    "The Last Exorcism",
    "The Devil's Advocate",
    "The Skeleton Key",
    "Cloverfield",
    "The Taking of Deborah Logan",
    "The House of the Devil",
    "V/H/S",
    "The Lords of Salem",
    "The Devil's Candy",
    "A Girl Walks Home Alone at Night",
    "The Wailing",
    "The Orphanage",
    "The Mist",
    "The Woman in Black",
    "The Grudge",
    "The Haunting",
    "The Evil Dead II",
    "The Texas Chainsaw Massacre 2",
    "The Conjuring 3",
    "Truth or Dare",
    "Annabelle",
    "Scary Stories to Tell in the Dark",
    "The Invisible Man",
    "Tucker and Dale vs. Evil",
    "The Autopsy of Jane Doe",
    "The Babadook",
    "The Witch",
    "Midsommar",
    "A Quiet Place Part II",
    "The Night House",
    "Candyman",
    "Malignant",
    "Old",
    "Last Night in Soho",
    "The Night Comes for Us",
    "The Platform",
    "Creep",
    "The Babysitter",
    "The Belko Experiment",
    "Ready or Not",
    "Gerald's Game",
    "The Conjuring",
    "Annabelle: Creation",
    "The Devil's Doorway",
    "The Other Side of the Door",
    "The Blackcoat's Daughter",
    "The Ritual",
    "The Wretched",
    "You’re Next",
    "The Lodge",
    "Cam",
    "The Devil's Candy",
    "The Conjuring 2",
    "The Nun",
    "Lights Out",
    "Truth or Dare",
    "The Dark and the Wicked",
    "Relic",
    "Spontaneous",
    "Rising Sun",
    "The Hidden",
    "Sea of Love",
    "Donnie Brasco",
    "The Boondock Saints",
    "The Long Goodbye",
    "A History of Violence",
    "Miami Vice",
    "The Road",
    "Training Day",
    "Zero Dark Thirty",
    "The Town",
    "Sin City",
    "Inside Man",
    "Fargo",
    "The Machinist",
    "The Nice Guys",
    "Mystic River",
    "L.A. Confidential",
    "Gosford Park",
    "Zodiac",
    "The Secret in Their Eyes",
    "The Place Beyond the Pines",
    "Prisoners",
    "A Most Violent Year",
    "Kiss Kiss Bang Bang",
    "The Girl with the Dragon Tattoo",
    "The Big Short",
    "Hereditary",
    "The Lighthouse",
    "The Invisible Man",
    "Tinker Tailor Soldier Spy",
    "The Lovely Bones",
    "Nocturnal Animals",
    "Wind River",
    "The Gentlemen",
    "The Disaster Artist",
    "American Hustle",
    "Silver Linings Playbook",
    "The Master",
    "A Beautiful Mind",
    "Doubt",
    "The Big Sick",
    "The Imitation Game",
    "Steve Jobs",
    "Moneyball",
    "The Social Network",
    "Whiplash",
    "12 Years a Slave",
    "Spotlight",
    "The Revenant",
    "Birdman",
    "Room",
    "La La Land",
    "Moonlight",
    "Get Out",
    "Three Billboards Outside Ebbing, Missouri",
    "The Shape of Water",
    "Black Panther",
    "Joker",
    "Once Upon a Time in Hollywood",
    "Parasite",
    "1917",
    "Ford v Ferrari",
    "Jojo Rabbit",
    "Knives Out",
    "The Irishman",
    "Dunkirk",
    "The Lighthouse",
    "Uncut Gems",
    "The Farewell",
    "Marriage Story",
    "Hustlers",
    "Midsommar",
    "Borat Subsequent Moviefilm",
    "The Trial of the Chicago 7",
    "Soul",
    "Promising Young Woman",
]  